config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do 
    member do
     put "like", to: "pins#upvote"
    end
   end

  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  acts_as_votable

  has_attached_file :image, styles: { medium: "500x500>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("RANDOM()")
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def new
    @pin = current_user.pins.build
   end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
     else
      render 'new'
    end
   end

   def edit
    @pin = Pin.find(params[:id])
   end

   def update
    if @pin.update(pin_params)
     redirect_to @pin, notice: "Pin was Successfully updated!"
    else
     render 'edit'
    end
   end

  def destroy
  @pin.destroy
  redirect_to root_path
 end

 def upvote
  @pin.upvote_by current_user
  redirect_back fallback_location: root_path
 end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
   end

   def find_pin
    @pin = Pin.find(params[:id])
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Pin Board", root_path, method: :get %>
      </div>
<% if user_signed_in? %>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to "New Pin", new_pin_path %>
    </li>
    <li>
      <%= link_to "Account", edit_user_registration_path %>
    </li>
    <li>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </li>
<% else %>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to "Sign Up", new_user_registration_path %>
    </li>
    <li>
      <%= link_to "Sign In", new_user_session_path %>
    </li>
  </ul>
  </div>
  </ul>
<% end %>
  </nav>
<div class="container">
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin,  html: { multipart: true } do |f| %> <% if
@pin.errors.any? %>
<div id="errors">
  <h2></h2>
  <%= pluralize(@pin.errors.count, "error") %> prevented this Pin from saving
  <ul>
    <% @pin.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group">
  <%= f.input :image, input_html: { class: 'form-control' } %>
</div>
<div class="form-group">
  <%= f.input :title, input_html: { class: 'form-control' } %>
</div>
<div class="form-group">
  <%= f.input :description, input_html: { class: 'form-control' } %>
</div>
<%= f.button :submit, class: "btn btn-primary" %> <% end %> 


app/views/pins/edit.html.erb
<div class="col-md-8 col-md-offset-2" id="edit_page">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Edit Your Pin</h1>
      </div>
      <div class="panel-body">
        <div class="current_image">
          <strong class="center">Current Image</strong>
          <%= image_tag @pin.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <h2>
          <%= link_to pin.title, pin %>
        </h2>
      </div>
    </div>
  <% end %>
</div>


app/views/pins/new.html.erb
<div class="col-md-6 col-md offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New form</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb



<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user"></p>
            Submitted by 
            <%= @pin.user.email %>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart">
                  <%= @pin.get_upvotes.size %>
                </span>
              <% end %>
              <%= link_to "Back", root_path, class: "btn btn-default", method: :get %>
              <% if  current_user == @pin.user %>
              <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
              <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %><% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>